extends: MH0386
queue_rules:
  - name: default
    update_method: merge
    allow_queue_branch_edit: true
    queue_branch_merge_method: fast-forward
    queue_conditions:
      - and:
          - 'check-success = DeepSource: Secrets'
          - 'check-success = DeepSource: Shell'
          - check-success = CodeFactor
          - check-success = GitGuardian Security Checks
          - check-success = CodeQL
          - check-success = prek
