return {
    description = "Cosmic DE",
    packages = {
        "cosmic-app-library",
        "cosmic-applets",
        "cosmic-bg",
        "cosmic-comp",
        "cosmic-files",
        "cosmic-greeter",
        "cosmic-idle",
        "cosmic-initial-setup",
        "cosmic-launcher",
        "cosmic-notifications",
        "cosmic-osd",
        "cosmic-panel",
        "cosmic-player",
        "cosmic-randr",
        "cosmic-screenshot",
        "cosmic-session",
        "cosmic-settings",
        "cosmic-settings-daemon",
        "cosmic-store",
        "cosmic-terminal",
        "cosmic-text-editor",
        "cosmic-workspaces",
        "xdg-desktop-portal-cosmic",
        "cosmic-wallpapers",
        "minimon-applet-for-cosmic",
        "cosmic-applet-music-player-git",
        "cosmic-applet-package-updater-git",
        "cosmic-ctl",
        "cosmic-ext-applet-caffeine-git",
        "cosmic-ext-applet-cpu-temperature",
        "cosmic-ext-applet-ollama-git",
        "cosmic-ext-applet-privacy-indicator",
        "cosmic-ext-applet-sysinfo-git",
        "cosmic-ext-applet-system-monitor-git",
        "cosmic-ext-forecast-git",
        "cosmic-ext-tweaks-git",
        "cosmic-icon-theme"
    },
    dotfiles_sync = true
}
