-- System packages module
-- Auto-synced by dcli merge

local packages = {
    "accountsservice",
    "alacritty",
    "alsa-firmware",
    "alsa-plugins",
    "alsa-utils",
    "bind",
    "bluez",
    "bluez-hid2hci",
    "bluez-libs",
    "bluez-obex",
    "bluez-utils",
    "btrfs-assistant",
    "btrfs-progs",
    "cachy-update",
    "chwd",
    { name = "com.vintagetechie.CosmicExtAppletCargoWatch", type = "flatpak" },
    "cpupower",
    "cryptsetup",
    { name = "dev.DBrox.CosmicPrivacyIndicator",            type = "flatpak" },
    { name = "dev.cappsy.CosmicExtAppletDrives",            type = "flatpak" },
    "diffutils",
    "dmidecode",
    "dmraid",
    "dnsmasq",
    "dosfstools",
    "duf",
    "e2fsprogs",
    "efibootmgr",
    "efitools",
    "egl-wayland",
    "espeak-ng",
    "ethtool",
    "exercism-bin",
    "exfatprogs",
    "f2fs-tools",
    "ffmpegthumbnailer",
    "fsarchiver",
    "fwupd",
    "gedit",
    "gemini-cli",
    "glances",
    "gst-libav",
    "gst-plugin-pipewire",
    "gst-plugin-va",
    "gst-plugins-bad",
    "gst-plugins-ugly",
    "hdparm",
    "hwdetect",
    "hwinfo",
    "inetutils",
    "intel-media-driver",
    "intel-media-sdk",
    { name = "io.github.cosmic_utils.cosmic-ext-applet-clipboard-manager",           type = "flatpak" },
    { name = "io.github.cosmic_utils.cosmic-ext-applet-external-monitor-brightness", type = "flatpak" },
    { name = "io.github.cosmic_utils.minimon-applet",                                type = "flatpak" },
    { name = "io.github.hepp3n.kdeconnect",                                          type = "flatpak" },
    "iptables-nft",
    "iwd",
    "jfsutils",
    "less",
    "lib32-vulkan-icd-loader",
    "lib32-vulkan-intel",
    "libdvdcss",
    "libgsf",
    "libnma",
    "libopenraw",
    "limine",
    "limine-mkinitcpio-hook",
    "limine-snapper-sync",
    "linux-firmware",
    "llmfit-bin",
    "logrotate",
    "lsb-release",
    "lsscsi",
    "lvm2",
    "man-db",
    "man-pages",
    "mdadm",
    "mesa-utils",
    "micro",
    "mkinitcpio",
    "modemmanager",
    "mousetweaks",
    "mtools",
    "nano",
    "nano-syntax-highlighting",
    "netctl",
    "networkmanager",
    "networkmanager-openvpn",
    "nfs-utils",
    "nilfs-utils",
    "notification-daemon",
    "nss-mdns",
    "openai-codex",
    "openssh",
    { name = "org.freedesktop.Platform",              type = "flatpak" },
    { name = "org.freedesktop.Platform",              type = "flatpak" },
    { name = "org.freedesktop.Platform.GL.default",   type = "flatpak" },
    { name = "org.freedesktop.Platform.GL.default",   type = "flatpak" },
    { name = "org.freedesktop.Platform.GL.default",   type = "flatpak" },
    { name = "org.freedesktop.Platform.GL.default",   type = "flatpak" },
    -- { name = "org.freedesktop.Platform.GL.nvidia-595-45-04", type = "flatpak" },
    { name = "org.freedesktop.Platform.VAAPI.Intel",  type = "flatpak" },
    { name = "org.freedesktop.Platform.VAAPI.Intel",  type = "flatpak" },
    { name = "org.freedesktop.Platform.VAAPI.nvidia", type = "flatpak" },
    { name = "org.freedesktop.Platform.codecs-extra", type = "flatpak" },
    { name = "org.freedesktop.Platform.openh264",     type = "flatpak" },
    "os-prober",
    "pacman-contrib",
    "pavucontrol",
    "perl",
    "pipewire-alsa",
    "pipewire-pulse",
    "pkgfile",
    "plocate",
    "plymouth",
    "poppler-glib",
    "power-profiles-daemon",
    "pv",
    "python-defusedxml",
    "python-packaging",
    "rebuild-detector",
    "reflector",
    "ripgrep",
    "rsync",
    "s-nail",
    "sg3_utils",
    "smartmontools",
    "socat",
    "sof-firmware",
    "sudo",
    "sysfsutils",
    "texinfo",
    "ufw-extras",
    "upower",
    "usb_modeswitch",
    "usbutils",
    "vim",
    "vlc-plugins-all",
    "vulkan-icd-loader",
    "vulkan-intel",
    "wget",
    "which",
    "winboat",
    "bottles",
    "wireplumber",
    "xfsprogs",
    "xl2tpd",
    "pip2pkgbuild",
    "xorg-xauth",
    "octopi"
}

return {
    description = "Packages installed manually on the system (auto-synced by dcli)",
    packages = packages,
}
