name: CI
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
permissions:
  contents: write
  pull-requests: write
  checks: write
  deployments: write
  security-events: write
  actions: read
jobs:
  prek:
    name: prek
    runs-on: ubuntu-latest
    environment: prek
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Run prek hooks
        uses: j178/prek-action@0bb87d7f00b0c99306c8bcb8b8beba1eb581c037 # v1.1.1
      - name: Commit prek changes
        uses: stefanzweifel/git-auto-commit-action@4a55954c782fc1ea30b9056cd3e7a2b40ca8887d # v7.2.0
        if: success() || failure()
        with:
          commit_message: 'prek: Apply fixes'
          commit_options: --no-verify
