name: CI
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
permissions:
  contents: write
  pull-requests: write
  checks: write
  deployments: write
  security-events: write
  actions: read
jobs:
  prek:
    name: prek
    runs-on: ubuntu-latest
    environment: prek
    steps:
      - name: Checkout repository
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Run prek hooks
        uses: j178/prek-action@0bb87d7f00b0c99306c8bcb8b8beba1eb581c037 # v1.1.1
      - name: Commit prek changes
        uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7.1.0
        if: success() || failure()
        with:
          commit_message: 'prek: Apply fixes'
          commit_options: --no-verify
